name: Auto-update Feature Branches

on:
  push:
    branches:
      - main

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all branches
        run: |
          git fetch origin --prune
          echo "All remote branches: $(git branch -r)" # Debug all remote branches
      - name: Get feature branches
        id: set-branches
        run: |
          # Match branches starting with 'feature' or 'feature-' followed by any characters
          branches=$(git branch -r | grep -E 'origin/feature[0-9a-zA-Z-]*' | sed 's/origin\///' | grep -v 'main' || echo "[]")
          echo "Matched branches: $branches" # Debug matched branches
          echo "branches=$branches" >> $GITHUB_OUTPUT

  update-feature-branches:
    needs: get-branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.branches) || '[]' }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - name: Update feature branch
        if: ${{ matrix.branch != '' }}
        run: |
          echo "Updating ${{ matrix.branch }}..."
          git checkout ${{ matrix.branch }}
          git rebase origin/main || {
            echo "Rebase failed for ${{ matrix.branch }}, attempting merge..."
            git rebase --abort
            git merge origin/main --no-edit
          }
          git push --force-with-lease